import Link from "next/link";

const courses = [["Learn Figma from Basic", "image1.png", "perla.victor"], ["Build Digital Asset", "image2.png", "perla.victor"], ["The Power of Big Data", "image3.png", "perla.victor"], ["Balancing Productivity with Joy", "image4.png", "perla.victor"], ["Mastering Money Management", "image2.png", "sarah.jones"], ["From Idea to Startup Success", "image1.png", "james.lee"]];
const categories = ["Featured", "Music", "Drawing & Painting", "Marketing", "Animation", "Social Media", "UI/UX Design", "Creative Marketing", "Digital Illustration", "Film & Video", "Crafts", "Freelance & Entrepreneurship", "Graphic Design", "Photography", "Productivity", "Web Development", "Data Science", "Cooking"];

function CourseCard({ course }) { return <Link className="course-card" href={`/courses/${course[0].toLowerCase().replaceAll(" ", "-")}`}><div className="thumb"><img src={`/assets/${course[1]}`} alt="" /><span className="lesson">17 Lessons　 2 hours 16 mins</span></div><div className="course-body"><div className="course-title"><strong>{course[0]}</strong><span>4.5 ★</span></div><small>by <em>{course[2]}</em></small><div className="avatars"><span>●</span><span>●</span><span>●</span><span>●</span><b>2k+</b></div><div className="price">$25 <small>/ lifetime</small></div></div></Link>; }

export default function CourseDiscovery() {
  return <section className="section" id="courses"><header><h2>Discover Your Passion,<br />Build Your Skills</h2><p>At Bytespace Courses, we bring you closer to life-changing knowledge. Explore a variety of courses across different<br className="desktop" /> fields, from technology to the arts, and make a difference in your career and life.</p></header><div className="chips">{categories.map((category, index) => <button className={index === 0 ? "active" : ""} key={category}>{category}</button>)}<button className="more">+ More</button></div><div className="course-grid">{courses.map((course, index) => <CourseCard course={course} key={`${course[0]}-${index}`} />)}</div></section>;
}
